# Generated by Django 5.2.5 on 2025-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emiratesidrecord',
            name='family_sponsor_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
