# Generated by Django 5.2.5 on 2025-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emiratesidrecord_family_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='dob',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='emirates_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='emirates_id_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='expiry',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='nationality',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='occupation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
