# Generated by Django 5.2.5 on 2025-10-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatsession_dob_chatsession_emirates_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='depender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
