# Generated by Django 5.2.5 on 2025-10-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatsession_depender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
