# Generated by Django 5.2.7 on 2025-11-03 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatsession_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('passport_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('given_name', models.CharField(blank=True, max_length=256, null=True)),
                ('surname', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.CharField(blank=True, max_length=32, null=True)),
                ('nationality', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=256, null=True)),
                ('date_of_issue', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_expiry', models.CharField(blank=True, max_length=32, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=128, null=True)),
                ('passport_type', models.CharField(blank=True, max_length=16, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('name_match', models.BooleanField(default=False)),
                ('expiry_valid', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport_record', to='api.chatsession')),
            ],
        ),
    ]
