# Generated by Django 5.2.5 on 2025-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAEDocumentVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('file_number', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_permit_no', models.CharField(blank=True, max_length=50, null=True)),
                ('employer_or_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('uid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
