# Generated by Django 5.2.5 on 2025-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_uaedocumentvisa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='employer_or_full_name',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='uaedocumentvisa',
            old_name='entry_permit_no',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='issuing_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uaedocumentvisa',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
